#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          28

bspc config focused_border_color  '#213882'
bspc config normal_border_color   '#2e3147'
bspc config presel_feedback_color '#d97706'

# cursor y recursos X
xrdb -merge ~/.Xresources
xsetroot -solid '#0d0f17' -cursor_name left_ptr

~/.config/polybar/launch.sh &

kitty &
